_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.03035633 -0.05235964 -0.07222111 -0.00777341 -0.00342782  0.0219975
           0.          0.          0.          0.          0.          0.
           0.81964743  0.2164269   0.06628276  0.502      -0.05       -0.1175
          -0.3176474  -0.2664269  -0.18378276  0.45349672  0.00966762  0.01667505
           0.02300035  0.00247561  0.00109166  0.00700557  0.          0.
           0.        ]
         [ 0.07597238  0.04539254  0.0489937  -0.05880177 -0.05730626  0.06660207
           0.          0.          0.          0.          0.          0.
           0.79013973  0.2520129  -0.06151664  0.502      -0.05       -0.1175
          -0.28813976 -0.3020129  -0.05598336  0.4211537   0.02419502  0.01445622
           0.01560309  0.01872668  0.0182504   0.02121085  0.          0.
           0.        ]
         [-0.07520269  0.01730845  0.08352528 -0.06169683  0.06882245  0.09630655
           0.          0.          0.          0.          0.          0.
           0.82920563  0.12932095 -0.05248073  0.502      -0.05       -0.1175
          -0.32720563 -0.17932095 -0.06501927  0.37874404  0.0239499   0.00551224
           0.02660041  0.01964867  0.02191798  0.03067088  0.          0.
           0.        ]
         [ 0.03872191 -0.02017281 -0.05812202 -0.07487637 -0.0105101   0.02550393
           0.          0.          0.          0.          0.          0.
           0.82151496  0.2234156   0.03473781  0.502      -0.05       -0.1175
          -0.31951496 -0.2734156  -0.15223782  0.44723848  0.01233182  0.00642446
           0.0185102   0.02384598  0.00334717  0.00812227  0.          0.
           0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x117680c80>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.3
        e:
            f83mqp77n1d61rq5dnmxerucyok9w4xm:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: PPO.py
                codePathLocal: PPO.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "248373436416"
                email: js6897@columbia.edu
                executable: /Users/jaiselsingh/Desktop/research/.venv/bin/python
                git:
                    commit: c03b56199c3ac37aff54830df2ef2c77a1411dcf
                    remote: git@github.com:jaiselsingh1/ur5_research.git
                host: Mac.lan
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jaiselsingh/Desktop/research/PPO.py
                python: CPython 3.12.5
                root: /Users/jaiselsingh/Desktop/research
                startedAt: "2025-09-03T03:41:48.218508Z"
                writerId: f83mqp77n1d61rq5dnmxerucyok9w4xm
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 22
                - 35
            "4": 3.12.5
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (6,), float64)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x10ee4af00>
env_id:
    value: UR5-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_std_init:
    value: -1.38
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_cpu:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (31,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''log_std_init'': -1.38}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x10ef1d640>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1756870910828473000
target_kl:
    value: None
tensorboard_log:
    value: tensorboard_log
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
