_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.02772275  0.06790366  0.0161791  -0.05164159 -0.0990268  -0.01800895
           0.          0.          0.          0.          0.          0.
           0.798078    0.21325083 -0.06695678  0.502      -0.05       -0.1175
          -0.29607797 -0.26325083 -0.05054322  0.39939678  0.0088289   0.02162537
           0.00515258  0.01644637  0.0315372   0.00573533  0.          0.
           0.        ]
         [ 0.07703301  0.03170185  0.09228099 -0.05550697 -0.02535836  0.03595052
           0.          0.          0.          0.          0.          0.
           0.7883474   0.2528421  -0.0671052   0.502      -0.05       -0.1175
          -0.28634745 -0.30284208 -0.0503948   0.41981882  0.0245328   0.01009613
           0.02938885  0.01767738  0.00807591  0.01144921  0.          0.
           0.        ]
         [-0.08446448  0.07293171 -0.04610844 -0.03345895 -0.01269658 -0.09782548
           0.          0.          0.          0.          0.          0.
           0.82880574  0.12195671 -0.04698453  0.502      -0.05       -0.1175
          -0.32680574 -0.1719567  -0.07051548  0.37595683  0.02689952  0.02322666
           0.01468422  0.01065572  0.0040435   0.03115461  0.          0.
           0.        ]
         [-0.04274869  0.0632774   0.08512992  0.06450777 -0.06214562 -0.02014082
           0.          0.          0.          0.          0.          0.
           0.79454726  0.15747948 -0.08714792  0.502      -0.05       -0.1175
          -0.29254726 -0.20747949 -0.03035208  0.35993457  0.01361423  0.02015204
           0.02711144  0.02054388  0.0197916   0.00641427  0.          0.
           0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x11fb15e20>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.3
        e:
            t9cmsncuc5b2q25cne1yx10ya20oqavd:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: PPO.py
                codePathLocal: PPO.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "248381050880"
                email: js6897@columbia.edu
                executable: /Users/jaiselsingh/Desktop/research/.venv/bin/python
                git:
                    commit: 162ba687d870ae3aef352438677f23c7f681c588
                    remote: git@github.com:jaiselsingh1/ur5_research.git
                host: Mac.lan
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/jaiselsingh/Desktop/research/PPO.py
                python: CPython 3.12.5
                root: /Users/jaiselsingh/Desktop/research
                startedAt: "2025-09-03T03:59:59.963990Z"
                writerId: t9cmsncuc5b2q25cne1yx10ya20oqavd
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
                - 22
                - 35
            "4": 3.12.5
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (6,), float64)
algo:
    value: PPO
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x119fae480>
env_id:
    value: UR5-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
log_std_init:
    value: -1.38
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_cpu:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (31,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=31, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''log_std_init'': -1.38}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x11c8f7470>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1756872002518507000
target_kl:
    value: None
tensorboard_log:
    value: tensorboard_log
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
